/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdminAppFooter: typeof import('./src/layout/admin/AppFooter.vue')['default']
    AdminAppLayout: typeof import('./src/layout/admin/AppLayout.vue')['default']
    AdminAppMenu: typeof import('./src/layout/admin/AppMenu.vue')['default']
    AdminAppMenuItem: typeof import('./src/layout/admin/AppMenuItem.vue')['default']
    AdminAppSidebar: typeof import('./src/layout/admin/AppSidebar.vue')['default']
    AdminAppTopbar: typeof import('./src/layout/admin/AppTopbar.vue')['default']
    AppLayout: typeof import('./src/layout/AppLayout.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Toast: typeof import('primevue/toast')['default']
  }
}
