/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
<<<<<<< HEAD
=======
    'root': RouteRecordInfo<'root', '/', Record<never, never>, Record<never, never>>,
    'produk': RouteRecordInfo<'produk', '/produk', Record<never, never>, Record<never, never>>,
    'produk-slug': RouteRecordInfo<'produk-slug', '/produk/:slug', { slug: ParamValue<true> }, { slug: ParamValue<false> }>,
>>>>>>> 3b7c66c3c565763e07b8659943530581d5f2d322
  }
}
